version: '3.6'
services: 
    postgres:
        image: postgres:14.8-alpine
        restart: always
        environment: 
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=Memories
            - POSTGRES_PASSWORD=Memories
            - POSTGRES_DB=Memories
        ports:
            - "9991:5432"
        volumes:
            - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql